/*
 * NewJFrame.java
 *
 * Created on June 7, 2010, 1:48 AM
 */

package network;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Insets;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.GrayFilter;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
/**
 *
 * @author  Raffan
 */
public class NewJFrame extends javax.swing.JFrame {

    final ImageIcon imageIcon = new ImageIcon("bangladesh.JPG");
    private final static String IMAGE_NAME = "scan"; // base image name    
    private final int TOTAL_IMAGES = 8;  // number of images
    private int currentImage = 0; // current image index
    private final int ANIMATION_DELAY = 90; // millisecond delay
    public int totalThread = 30;
    int totalSensor = 0, totalClient = 0,tick=0;
    private javax.swing.Timer animationTimer;
    public ArrayList<String> connected_clients =  new ArrayList<String>();
    public ArrayList<String> sensorList = new ArrayList<String>();
    public ArrayList<String> sensorId = new ArrayList<String>();
    public ArrayList<String> sensorLocation= new ArrayList<String>();//the location,eg:dhaka...etc
    public ArrayList<String> sensorPositions = new ArrayList<String>();//the coordinate of the sensor on the map
    public ArrayList<String> sensorData = new ArrayList<String>();
    public ArrayList<JLabel> sensorLabel = new ArrayList<JLabel>();
    public ArrayList<String> connectedSensorList = new ArrayList<String>();
    public ArrayList<String> subscriberList = new ArrayList<String>();
    public ArrayList<String> subscriberId = new ArrayList<String>();
    public ArrayList<String> connectedSubscriberList = new ArrayList<String>();
    public ArrayList<ServerThread> subscriberHandlerThread = new ArrayList<ServerThread>();
    public ArrayList<Integer> isConnectedSubscriber = new ArrayList<Integer>();
    public ArrayList<String> choiceList = new ArrayList<String>();
    
    
    public Server server;
    /** Creates new form NewJFrame */
    //private UIManager.LookAndFeelInfo looks[];
    public NewJFrame() {
        //setLabels();
        initComponents();
        usercode();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel()

        ;
        jPanel3 = new javax.swing.JPanel()
        {
            Image image = imageIcon.getImage();
            Image grayImage = GrayFilter.createDisabledImage(image);
            {setOpaque(false);}  // instance initializer
            public void paintComponent (Graphics g) {
                g.drawImage(image, 0, 0, this);
                super.paintComponent(g);
            }
        }
        ;
        jPanel6 = new javax.swing.JPanel();
        jTextField2_location = new javax.swing.JTextField();
        jTextField3_latitude = new javax.swing.JTextField();
        jTextField4_longitude = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Connected_Subscribers = new javax.swing.JList();
        jLabel54 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        All_Subscribers = new javax.swing.JList();
        jLabel51 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Connected_Sensors = new javax.swing.JList();
        jLabel53 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        All_Sensors = new javax.swing.JList();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Sensor"));

        jTextField3_latitude.setEditable(false);

        jTextField4_longitude.setEditable(false);

        jLabel1.setText("Location");

        jLabel2.setText("Latitude");

        jLabel3.setText("Longitude");

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setEnabled(false);
        jScrollPane6.setPreferredSize(new java.awt.Dimension(146, 96));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(10);
        jTextArea2.setRows(5);
        jTextArea2.setText("To create a sever, enter\na name in the location box,\nthen click on the map where \nyou want to place the sensor\nto get the latitude-longitude.");
        jTextArea2.setToolTipText("");
        jTextArea2.setAlignmentX(10.0F);
        jTextArea2.setAutoscrolls(false);
        jTextArea2.setDoubleBuffered(true);
        jTextArea2.setEnabled(false);
        jScrollPane6.setViewportView(jTextArea2);

        jButton2.setText("Create");
        jButton2.setMaximumSize(new java.awt.Dimension(71, 29));
        jButton2.setMinimumSize(new java.awt.Dimension(71, 29));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField2_location, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField3_latitude, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField4_longitude, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2_location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3_latitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4_longitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/network/red.png"))); // NOI18N
        jLabel5.setText("Server offline");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/network/green.png"))); // NOI18N
        jLabel6.setText("Server online");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Map", jPanel1);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Clients"));

        jLabel52.setText("Connected Subscribers");

        jScrollPane2.setViewportView(Connected_Subscribers);

        jLabel54.setText("All Subscribers");

        jScrollPane4.setViewportView(All_Subscribers);

        jLabel51.setText("Connected Sensors");

        jScrollPane1.setViewportView(Connected_Sensors);

        jLabel53.setText("All Sensors");

        jScrollPane3.setViewportView(All_Sensors);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel53)
                    .addComponent(jLabel51)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel52))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel54)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(jLabel51))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel54)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Subscriber"));

        jButton1.setText("Create");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Subscriber Name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Connections", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
 
   //Server application = new Server(this);  
    server.stop = true;
    System.exit(0);
   
}//GEN-LAST:event_jButton4ActionPerformed

private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked

    //jTextArea1.append("\n"+evt.getX()+"  "+evt.getY());
    if(!(jTextField2_location.getText().equals("")))
    {
        jTextField3_latitude.setText(""+evt.getX());
        jTextField4_longitude.setText(""+evt.getY());    
    }
    
}//GEN-LAST:event_jPanel3MouseClicked

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    if(!(jTextField3_latitude.getText().trim().equals("")))
    {    
        totalSensor++;        
        sensorList.add(jTextField2_location.getText().trim()+" "+String.valueOf(totalSensor));
        sensorLocation.add(jTextField2_location.getText().trim());
        sensorId.add(String.valueOf(totalSensor));
        sensorPositions.add(jTextField3_latitude.getText().trim()+" "+jTextField4_longitude.getText().trim());
        sensorData.add("null null");
        create_sensor_label(totalSensor-1);
        
        jTextField2_location.setText("");
        jTextField3_latitude.setText("");
        jTextField4_longitude.setText("");
        
        refreshLists(sensorList,All_Sensors,1);
        //refreshLists(subscriberList,All_Subscribers,1);
        refreshSubscriberAndchoice();
        
        notify_all_subscribers();
    }
        
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    String name = jTextField1.getText();
    if(!(name.equals("")))
    {
        totalClient++;        
        subscriberList.add(name + " "+String.valueOf(totalClient));
        subscriberId.add(String.valueOf(totalClient));
        choiceList.add("all");
        refreshSubscriberAndchoice();
        jTextField1.setText("");
    
    }
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    public void usercode() 
    {   
        this.setTitle("Server");
        server = new Server(this);
                
        setUI();       
        someClient();
       
        someSensor();
        
        refreshLists(sensorList,All_Sensors,1);
        //refreshLists(subscriberList,All_Subscribers,1);
        refreshSubscriberAndchoice();
        
    }
    public void setUI()
    {
        try
        {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");           
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception  exception)
        {
            exception.printStackTrace();
        }   
    }    
   
    public void setLabels()
    {
        int n = jPanel3.getComponentCount();
        System.out.println(""+n);

        //JComponent com ;
        JLabel  label;
        for(int i=0;i<sensorList.size();i++)
        {
            label = (JLabel) jPanel3.getComponent(i);
            
            label.setVisible(true);
            StringTokenizer location = new StringTokenizer(sensorPositions.get(i)," ");
            int x = Integer.parseInt(location.nextToken());
            int y = Integer.parseInt(location.nextToken());
            label.setLocation(x, y);
           
        }
        
    }
    
  
    public void someClient()
    {
        totalClient++;        
        subscriberList.add("Client1 "+String.valueOf(totalClient));
        subscriberId.add(String.valueOf(totalClient));
        choiceList.add("Dhaka Barisal Sylhet");
        
        totalClient++;         
        subscriberList.add("Client2 "+String.valueOf(totalClient));
        subscriberId.add(String.valueOf(totalClient));
        choiceList.add("all");
        
        totalClient++;         
        subscriberList.add("Client3 "+String.valueOf(totalClient));   
        subscriberId.add(String.valueOf(totalClient));
        choiceList.add("Dhaka Rajshahi Chittagong");
    }    
    
    public void someSensor()
    {
        totalSensor++;        
        sensorList.add("Dhaka "+String.valueOf(totalSensor));
        sensorLocation.add("Dhaka");
        sensorId.add(String.valueOf(totalSensor));
        sensorPositions.add("280 344");
        sensorData.add("27 30");
        create_sensor_label(totalSensor-1);
        
        totalSensor++;        
        sensorList.add("Khulna "+String.valueOf(totalSensor));
        sensorLocation.add("Khulna");
        sensorId.add(String.valueOf(totalSensor));
        sensorPositions.add("181 513");
        sensorData.add("40 50");
        create_sensor_label(totalSensor-1);
        
        totalSensor++;        
        sensorList.add("Chittagong "+String.valueOf(totalSensor));
        sensorLocation.add("Chittagong");
        sensorId.add(String.valueOf(totalSensor));
        sensorPositions.add("474 506");
        sensorData.add("10 20");
        create_sensor_label(totalSensor-1);
       
        totalSensor++;        
        sensorList.add("Sylhet "+String.valueOf(totalSensor));
        sensorLocation.add("Sylhet");
        sensorId.add(String.valueOf(totalSensor));
        sensorPositions.add("497 231");
        sensorData.add("30 40");
        create_sensor_label(totalSensor-1);
        
        totalSensor++;        
        sensorList.add("Rajshahi "+String.valueOf(totalSensor));
        sensorLocation.add("Rajshahi");
        sensorId.add(String.valueOf(totalSensor));
        sensorPositions.add("70 264");
        sensorData.add("50 50");
        create_sensor_label(totalSensor-1);
        
        totalSensor++;        
        sensorList.add("Barisal "+String.valueOf(totalSensor));
        sensorLocation.add("Barisal");
        sensorId.add(String.valueOf(totalSensor));
        sensorPositions.add("279 461");
        sensorData.add("10 50");
        create_sensor_label(totalSensor-1);
    }

    synchronized public void refreshLists(ArrayList<String> alist, JList jlist, int incr)
    {
        DefaultListModel model = new DefaultListModel();
        jlist.removeAll();
        
        
        for(int i=0;i<alist.size();)
        {
            //model.add(i, alist.get(i));
            model.addElement(alist.get(i));
            i=i+incr;
        }
        
        jlist.setModel(model);
        
    }
    
     synchronized public void refreshSubscriberAndchoice()
    {
        DefaultListModel model = new DefaultListModel();
        
        All_Subscribers.removeAll();
        
        for(int i=0;i<subscriberList.size();i++)
        {
            model.addElement(subscriberList.get(i));
            model.addElement("=================");
            model.addElement("Subscribes for:\n");
            
            model.addElement(choiceList.get(i));
            model.addElement("\n\n");
            
        }
        
        All_Subscribers.setModel(model);
        
    }
    
    public void create_sensor_label(int index)
    {
        javax.swing.JLabel label = new JLabel("asd");
    
        label.setVisible(true);
    
        label.setVisible(true);
        Container pane = this.getContentPane();

        pane.setLayout(null);
        pane.add(label);
        jPanel3.add(label);
        jPanel3.revalidate();
        jPanel3.repaint();
       
        Insets insets = pane.getInsets();
        Dimension size = label.getPreferredSize();
        label.setBounds(0 + insets.left, 0 + insets.top,size.width, size.height);
        
        StringTokenizer coord = new StringTokenizer(sensorPositions.get(index)," ");
        int x = Integer.parseInt(coord.nextToken()); 
        int y = Integer.parseInt(coord.nextToken()); 
        
        System.out.println("In the create sensor "+x+" "+y);
        //label.setLocation(x, y);
        label.setLocation(x, y);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("red.png")));
        sensorLabel.add(label);
        
    }
    
    synchronized public void notify_all_subscribers()
    {
        for(int i=0;i<subscriberHandlerThread.size();i++)
        {
            subscriberHandlerThread.get(i).send_sensor_update_notification();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList All_Sensors;
    public javax.swing.JList All_Subscribers;
    public javax.swing.JList Connected_Sensors;
    public javax.swing.JList Connected_Subscribers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2_location;
    private javax.swing.JTextField jTextField3_latitude;
    private javax.swing.JTextField jTextField4_longitude;
    // End of variables declaration//GEN-END:variables

}
